name: React to build

on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches:
      - 'test-*'
      - 'main'

jobs:
  on-sucess:
    runs-on: ubuntu-latest
    steps:
      - name: Responds do "Hi"
        run: |
          echo "Ohai!"
